# Config file for automatic testing at travis-ci.org

# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - master

# Prefer docker containers
sudo: required

language: python

python:
  - "2.7"

cache: pip

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "2.7"
    env: TOXENV=py27-flake8
  - python: "3.4"
    env: TOXENV=py34-flake8

install:
  - travis_retry pip install --upgrade pip setuptools tox

script:
  - tox

before_cache:
  - scripts/remove-old-files.py -o 180 ~/.cache/pip
