# Test on windows
# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
version: '{branch}-{build}'

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# Match travis
clone_depth: 50

environment:
  matrix:
    - TOXENV: "py27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python27"
    - TOXENV: "py36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python36"
    - TOXENV: "py36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python36-x64"
    - TOXENV: "py37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python37"
    - TOXENV: "py37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python37-x64"
    - TOXENV: "py38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python38"
    - TOXENV: "py38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python38-x64"
    - TOXENV: "py39"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python39"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - TOXENV: "py39"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python39-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - TOXENV: "py27-flake8"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python27"
    - TOXENV: "py39-flake8"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python39-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

install:
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"
  - "SET TOXPYTHON=%PYTHON_HOME%\\python.exe"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade \"pip<21\" \"setuptools<44\""
  - "pip install --upgrade \"tox<3.1\" ppu"
  - "pip --version"

# No build step - we don't have C extensions
build: false

test_script:
  - "tox"

after_test:
  - "scripts\\remove-old-files.py -o 180 %LOCALAPPDATA%\\pip\\Cache"
