name: Run tests

on: [push, pull_request]

jobs:
  run-tests:
    env:
      not_in_conda: "['3.11', 'pypy-3.7']"

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.7"]
        include:
        - os: ubuntu-latest
          os-name: Linux
          pip-cache-path: ~/.cache/pip
        - os: windows-latest
          os-name: w32
          pip-cache-path: ~\AppData\Local\pip\Cache

    name: Python ${{ matrix.python-version }} @ ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps:

      # Setup Python/pip
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python-version }}
        if: ${{ runner.os == 'Linux' && !contains(fromJSON(env.not_in_conda), matrix.python-version) }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        if: ${{ runner.os != 'Linux' || contains(fromJSON(env.not_in_conda), matrix.python-version) }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ matrix.pip-cache-path }}
          key: ${{ runner.os }}-pip

      # Setup tox
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          pip --version
          pip install --upgrade virtualenv tox
      - name: Set TOXENV
        run: |
          import os, sys
          if hasattr(sys, 'pypy_version_info'):
            toxenv = 'pypy3'
          else:
            pyver = '%d%d' % tuple(sys.version_info[:2])
            toxenv = 'py%s' % pyver
            if os.name == 'posix':
              toxenv += ',py%s-flake8' % pyver
          with open(os.environ['GITHUB_ENV'], 'a') as f:
            f.write('TOXENV=' + toxenv + '\n')
        shell: python

      - name: Run tox
        run: |
          python -c "import os; print(os.environ['TOXENV'])"
          tox --version
          tox
